# Generated by Django 2.1.4 on 2019-06-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('enroll', models.CharField(max_length=20)),
                ('depart', models.BooleanField()),
                ('msg', models.CharField(max_length=200)),
            ],
        ),
    ]
