# Generated by Django 2.1.4 on 2019-06-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='grievance_id',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('Not Solved', 'Not Solved')], default='Not Solved', max_length=6),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='depart',
            field=models.CharField(choices=[('Academics', 'Academics'), ('Hostel', 'Accomodation')], default='Academics', max_length=6),
        ),
    ]
