# Generated by Django 2.1.4 on 2019-06-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
