# Generated by Django 2.1.4 on 2019-06-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190605_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='grievance_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
