# Generated by Django 2.1.4 on 2019-06-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_grievance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='depart',
            field=models.BooleanField(default=False),
        ),
    ]
