# Generated by Django 2.1.4 on 2019-06-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190603_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='depart',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='status',
        ),
    ]
