# Generated by Django 2.1.4 on 2019-06-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190603_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='depart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grievance',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
