# Generated by Django 2.1.4 on 2019-06-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190603_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='depart',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
